### ISSUE TITLE
usersテーブルのカラムを見直す

### ISSUE THREAD

**Issue by k-kudo-hub** [k-kudo-hub/error_note_sample#14]
https://app.diagrams.net/#G1XuJg1231mx1mxZoYcjkIQFzhAOj3LXww
（Page1が現在の状態、Page2がこのissueでのアイディア）

現状ではkanaを用いているが、エラーをログするだけのアプリに必要以上の個人情報はいらない気がした。（他アプリにおいてもkanaを収集するものはごくわずか）
kanaカラムを削除し、最低限のプロフィール要素としてintroduce（自己紹介）とpicture（画像）を追加するのはどうだろうか。
nameもnicknameとかでもいいかも？

**Comment by toshiro-koba** [comment]
> kanaカラムを削除し、最低限のプロフィール要素としてintroduce（自己紹介）とpicture（画像）を追加するのはどうだろうか。

賛成！
> nameもnicknameとかでもいいかも？

`name`はそのままで大丈夫かなと思う！

**Comment by k-kudo-hub** [comment]
じゃあそんな感じでいきましょ！
nameはそのままで、kana削除、introduce(text)とpicture(text)を追加で🔥

**Comment by toshiro-koba** [comment]
よし！今週順にはPR立てます〜

**Comment by k-kudo-hub** [comment]
かたじけない！よろしくお願いいたします🙏

**Comment by k-kudo-hub** [comment]
@toshiro-koba 
多分先にauthenticate取り掛かるよね？
こっち俺の方でやっちゃいます笑

**Comment by toshiro-koba** [comment]
大変助かります！🙇🙇🙇
