### ISSUE TITLE
ログ機能の画面遷移を変更する

### ISSUE THREAD

**Issue by k-kudo-hub** [k-kudo-hub/error_note_sample#17]
## 課題
現状ログ機能はnew・editに成功するとそれぞれcreate・update画面に遷移する。
画面を挟む分、遷移が多くユーザビリティが低い。

## アプローチ
create画面を廃止し、users#showに遷移する方法に修正した方が良さそう。
遷移がひとつ減るため、多少は使いやすくなる。

**Comment by k-kudo-hub** [comment]
redirect_toの変更とビューファイルの削除なので、適当なIssueで同時にやってもいいかも😇笑

**Comment by toshiro-koba** [comment]
> redirect_toの変更とビューファイルの削除なので、適当なIssueで同時にやってもいいかも😇笑

このissueでやっちゃおう！💪

**Comment by k-kudo-hub** [comment]
かしこまった！💪
