### ISSUE TITLE
ログ作成画面の言語選択部分を調整する

### ISSUE THREAD

**Issue by k-kudo-hub** [k-kudo-hub/error_note_sample#31]
- 言語選択部分をリサイズ・調整
- 今後選択できる言語が増えた場合に対応可能にする

**Comment by toshiro-koba** [comment]
issueの本筋とは少しずれた余談にはなりますが、
今後、`選択項目`数を増加させるときはマイグレーションで追加した方が環境を合わせやすいと考えています。

別の方法として、`選択項目`を変更する用のview等で更新する方法もありますが、
そうなるとお互いのlocal環境で差異が生じやすくなるからです。

なのでマイグレーションで`選択項目`を適宜更新していければなーと思います。
ぜひ工藤さんの意見も聞きたいです。
急ぎではないので、お手隙の際にコメントいただければ嬉しいです🙇

**Comment by k-kudo-hub** [comment]
ごめん！閉じちゃったので言語選択部分の追加方法についてIssue立てます！
