### ISSUE TITLE
静的解析ツールrubocopの導入

### ISSUE THREAD

**Issue by toshiro-koba** [k-kudo-hub/error_note_sample#35]
コードの品質を担保する一助としてrubocopを導入したい。
`.rubocop.yml`の設定は都度改善していく。
導入タイミングとしてはPhase1(4/30)までにできたら良いなと思ってます。

PRは #33 を利用する予定です。

**Comment by k-kudo-hub** [comment]
基本的な機能とUIの実装が終わり次第導入できればと思う🙆‍♂️
ログ検索機能、UIの調整、authenticate処理とかが完成したら是非導入したい

**Comment by toshiro-koba** [comment]
> ログ検索機能、UIの調整、authenticate処理とかが完成したら是非導入したい

了解です！
#29 #32 サインインしないと機能使えないようにしてから導入しよう！

**Comment by k-kudo-hub** [comment]
そだね！Front側で修正しちゃおうか？

**Comment by k-kudo-hub** [comment]
でももうPR投げちゃってるから、authenticate 処理は別でissue作ろうか

**Comment by toshiro-koba** [comment]
> そだね！ #32 はFront側で修正しちゃおうか？

そうね！該当の全PRをマージしてからやろう！

> でももうPR投げちゃってるから、authenticate 処理は別でissue作ろうか

issueざっくりで大丈夫でいいので作ってくれるとありがたい！
実装はこっちでやりまっする！

**Comment by k-kudo-hub** [comment]
すまねぇ！ではIssue作ります！

**Comment by k-kudo-hub** [comment]
#51 がMergeされたら、該当のPRでもう一回rubocop回す感じにしようか💡

**Comment by toshiro-koba** [comment]
追記：
# rubocopを回すルール
`rubocop --fail-level W --display-only-fail-level-offenses`
基本はこれを実行。

PRではW以上は解決する方針。
オプション無しrubocopは任意で大丈夫。
後からリファクタリングのPR出すなど柔軟に対応する。

# 理由
テンポ良くやりたいから。
ただ、どんなコードがruby, railsにとってベストプラクティスなのか実装を通して知りたい狙いはある。
なので、デフォルトのrubocop違反基準が「厳しすぎる」「この基準は納得いかない」などあれば、
その度に話し合ってルールを決めることができたらいいなと思ってます。
