### ISSUE TITLE
ログの削除機能を作る

### ISSUE THREAD

**Issue by toshiro-koba** [k-kudo-hub/error_note_sample#36]
# やること
- ログを削除できるようにする
- 削除ボタンを仮設置
- 削除は作成者のみ可能

# いつやるか
4月中がいいと思う。
先に実装したいものがあれば教えてほしい！

**Comment by k-kudo-hub** [comment]
即やろう！笑
ログインしていて、本人だった場合は削除可能で！
また適当にボタンを置いておいてもらえると助かります…🙏

**Comment by toshiro-koba** [comment]
おっけい！
4/27までにはやります！
ちょっと遅延するかもしれないけどそのときは申し訳ねえ！

**Comment by k-kudo-hub** [comment]
全然大丈夫！
よろしくお願いします！🙏
