### ISSUE TITLE
Authenticate（ログイン誘導）処理の実装

### ISSUE THREAD

**Issue by k-kudo-hub** [k-kudo-hub/error_note_sample#37]
## Issueの概要
- ログインしていない場合、特定のページに遷移しようとした際はログインページに遷移するようリダイレクトを設定する

## 議論ポイント
- Authenticate処理が必要なアクションを書き出す✍️
- ログイン後、元のページに遷移するのか、users#showに飛ばすのか決める

## 別Issueでもいいが実現したい処理
- 自分以外のログについて、編集・削除できないようにする（「パスを直接叩く」対策）
- 自分のログをストックできないようにする（「パスを直接叩く」対策）

**Comment by k-kudo-hub** [comment]
## リダイレクトリスト

- [ ] ストック機能
    - [ ] ストックする（stocks#create）
    - [ ] ストックを解除する（stocks#destroy）

- [ ] ログ機能
    - [ ] ログを作成する（logs#new, logs#create）
    - [ ] ログを編集する（logs#edit, logs#update）
    - [ ] ログを削除する（logs#destroy）

**Comment by toshiro-koba** [comment]
洗い出しありがとう！！助かります！🙏

リダイレクトについてなんだけど、
- ビューにはログインしてなくても`ログを作成する`ボタンはある
- ただし、ログインしてない場合はサインインページに遷移させる。
- 他のリンクはそもそもビューには表示させない(`user_signed_in?`で弾く)
- URLを直接叩かれた時ようにコントローラーに分岐処理を書く

このように実装しようと思うけど、どうだろうか？

> 別Issueでもいいが実現したい処理

このissueでさくっとやっちゃいたいね！

**Comment by k-kudo-hub** [comment]
> ビューにはログインしてなくてもログを作成するボタンはある
> ただし、ログインしてない場合はサインインページに遷移させる。
> 他のリンクはそもそもビューには表示させない(user_signed_in?で弾く)
> URLを直接叩かれた時ようにコントローラーに分岐処理を書く

これで行こう！できればstockするボタンもそうしたいけど難しいかな？

**Comment by toshiro-koba** [comment]
おっけい！
ストックもビューに表示しないようにして、
コントローラーで不正なユーザーだったら保存できないようにします！

**Comment by k-kudo-hub** [comment]
ごめん！ストックは表示したいという意味でした🙏
わかりにくくて申し訳ない🙇‍♂️💦

**Comment by toshiro-koba** [comment]
了解！！
それなら簡単に実装できると思うのでそうします！
ありがとう！😘
