### ISSUE TITLE
ログ機能の言語選択肢の追加方法について議論

### ISSUE THREAD

**Issue by toshiro-koba** [k-kudo-hub/error_note_sample#41]
# 議論したいこと
言語選択肢を追加する手段を決めたい

## 提案
現状と同様にマイグレーションで定数として追加していく。

### 提案理由

今後、`選択項目`数を増加させるときはマイグレーションで追加した方が環境を合わせやすいと考えています。

別の方法として、`選択項目`を変更する用のview等で更新する方法もありますが、
そうなるとお互いのlocal環境で差異が生じやすくなるからです。

なのでマイグレーションで`選択項目`を適宜更新していければなーと思います。
ぜひ工藤さんの意見も聞きたいです。
急ぎではないので、お手隙の際にコメントいただければ嬉しいです🙇

\# TODO
- [ ] この話に進展があればmiroに記録する

**Comment by k-kudo-hub** [comment]
提案ありがとう！
マイグレーションの仕組みに疎くて申し訳ないんだけど、マイグレーションで追加した場合はid（language.id）に変更が生じたりするかな？
生じるのであれば、既に保存してあるデータとの齟齬でエラーが発生するリスクもあるかなと思いました。
DBに保存する以上、SQLインジェクション等の攻撃を想定しておく必要もあるね。
idに変更が生じないようであれば、引き続きマイグレーションでいくのが無難かなと思います。

**Comment by k-kudo-hub** [comment]
方法から考えるのであれば、find_or_createみたいなのも面白いかも。
DBに存在すればその言語のidを、存在しなければ新規作成みたいなフォーム形式とか。

**Comment by toshiro-koba** [comment]
> 提案ありがとう！
マイグレーションの仕組みに疎くて申し訳ないんだけど、マイグレーションで追加した場合はid（language.id）に変更が生じたりするかな？
生じるのであれば、既に保存してあるデータとの齟齬でエラーが発生するリスクもあるかなと思いました。
DBに保存する以上、SQLインジェクション等の攻撃を想定しておく必要もあるね。
idに変更が生じないようであれば、引き続きマイグレーションでいくのが無難かなと思います。

あー、選択肢を削除するときはid変わるなあ多分。
https://github.com/k-kudo-hub/error_note_sample/blob/2ad9f32e4e6d42922d239d9db00e338902e22afd/db/migrate/20210420151751_insert_initial_language.rb#L3
ここで配列として定義してlanguageを登録してるから、1個要素を削除するとidもずれる。
別のやり方を考えたほうがいいかも。

**Comment by toshiro-koba** [comment]
> 方法から考えるのであれば、find_or_createみたいなのも面白いかも。
DBに存在すればその言語のidを、存在しなければ新規作成みたいなフォーム形式とか。

`find_or_create`はどこかしらで使いたいね！
qiitaのタグ登録みたいな感じでユーザーがタグ自由に作ったりするならマイグレーションは向いてないかなと思います。
今後消すことはないものならマイグレーションで定数として随時追加していくのはアリだと思います。
プログラミング言語を選択するならサービス提供側で不変の定数(追加はあり)として提示するのがベターな気がするけど、どうなんかなあ。
こちらでそういう選択肢の定義方法について調べてみます！

**Comment by k-kudo-hub** [comment]
そうだよね〜、タグってのもなんかフワフワしてるんだよな。
不変の定数で行きたいけど、マイグレーションだとズレのリスクがあると…。
こっちでも色々調べてみる！👍

**Comment by k-kudo-hub** [comment]
アプリケーションのスタンスとしてはタグっていうより言語で確実に検索したい。
あくまで個人的な意見だけど、自由なタグ付けは今のところ頭にないですな😅

**Comment by toshiro-koba** [comment]
> アプリケーションのスタンスとしてはタグっていうより言語で確実に検索したい。
あくまで個人的な意見だけど、自由なタグ付けは今のところ頭にないですな😅

俺もそんな感じに思ってる〜。
ユーザーの表記揺れに振り回されたくないしw

とりあえず、カラムについての認識のすり合わせはできたし、あとは実装方法だね〜

**Comment by k-kudo-hub** [comment]
そうだね、選択肢としてどんな形があるか調べて書き出してみようか

**Comment by toshiro-koba** [comment]
とりあえず4/30までには決めたいね！

ちなみにプログラミング言語一覧、めっちゃあるw
仮に全部登録したとしても8割は1回使われなそうw
https://ja.wikipedia.org/wiki/%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0%E8%A8%80%E8%AA%9E%E4%B8%80%E8%A6%A7

**Comment by k-kudo-hub** [comment]
そうだね！4/30までには実装方法を固めよう。
A,B,C全部あるとは…‼︎😇
頻出のやつを選択肢として表示して、それ以外は隠しておいても良いかもね笑

**Comment by toshiro-koba** [comment]
そうね！
正直エラーの環境(dbms, OSのバージョン, フレームワーク)ってキリがない気もするから一回洗い出しが必要かも。
また今度打ち合わせしよう！

**Comment by toshiro-koba** [comment]
こちらのissueは以下で議論するのでcloseします。
#53
