### ISSUE TITLE
ヘッダーのデザインを調整する

### ISSUE THREAD

**Issue by k-kudo-hub** [k-kudo-hub/error_note_sample#48]
## 実現したいこと
- ヘッダーに検索フォームを組み込む
- 「記録する」リンクをアイコンに変更
- 「マイページ」リンクを画像に変更

## 実装のタイミング
- スタイル調整だけなので、いつでも取り掛かれます🙆‍♂️

**Comment by k-kudo-hub** [comment]
取り掛かっちゃっていいかな？

**Comment by toshiro-koba** [comment]
スタイリング助かります〜！
取り掛かりOKです！
お手隙の際にお願いします🙇

余談ですがUI改善されるたびにテンション上がってます笑

**Comment by k-kudo-hub** [comment]
おけ！ブランチ切ります🔥

ありがとう！これからもっと良くしていくから！💪
