### ISSUE TITLE
ページネーションの設定

### ISSUE THREAD

**Issue by k-kudo-hub** [k-kudo-hub/error_note_sample#51]
## 実現したいこと
- ログ一覧部分にページネーションを設定する

## 実現の方法
- gem kaminari の使用がベタかな

## 実装のタイミング
- Vue.jsの本格的な実装よりは前に取り掛かりたい

**Comment by toshiro-koba** [comment]
> gem kaminari の使用がベタかな

kaminariが使いやすいと思います。

> Vue.jsの本格的な実装よりは前に取り掛かりたい

そうですね。Phase1の内にやりましょう！
