### ISSUE TITLE
Languageの初期データを決定する。

### ISSUE THREAD

**Issue by toshiro-koba** [k-kudo-hub/error_note_sample#53]
#41　の続きです。

# このissueでやること
- 初期データとして投入するプログラミング言語一覧を選定する。
- 初期データ投入方法を決める。
- 今後追加で投入する方法を決める。

### migrationとして投入する
現在、暫定的にLogsテーブルに保存しているlanguageのレコードたちを`Log.destroy_all`で削除し、
主キーを1から始める為に、SQL文`alter table languages auto_increment = 1;`を実行する。
そして、`languages = %w(Bar Baz Foo)`のようにプログラミング言語名のリストを定義する。(予め昇順でsortしたものをここで定義する)

追加投入する時は、migrationで新しくレコードを1つ追加する。(2言語追加したいときは2つ)
既に保存しているレコードは削除しない(`Log.destroy_all`は実行しない。create文だけchangeメソッド内で実行する)

## 初期データ案
以下の言語がメジャーどころでいいかなと思ってます。
適宜追加及び除外していきたいのでご助言いただきたいです🙇
- C
- COBOL
- C#
- C++
- Go
- JavaScript
- Java
- Kuin
- Kotlin
- LISP
- MATLAB
- Node.js
- Perl
- PHP
- Python
- R
- Ruby
- Rust
- Scala
- Swift
- TypeScript
- Visual Basic .NET

KuinとLISPは僕の独断と偏見で入れました笑(厳選するなら消して大丈夫です)
また、言語のバージョンに関しては管理が煩雑になりそうなので考えてません。(この前議論しましたね)

FYI
[プログラミング言語一覧 \- Wikipedia](https://ja.wikipedia.org/wiki/%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0%E8%A8%80%E8%AA%9E%E4%B8%80%E8%A6%A7)
[Kuinのダウンロードと紹介 \- プログラミング言語「Kuin」](https://kuina.ch/kuin/download)

**Comment by k-kudo-hub** [comment]
Issueありがとう！
zshってCだよね？あんまり詳しくないけどいらない気がした笑
Rとかあってもいいのかな。

**Comment by toshiro-koba** [comment]
zshはシェルスクリプトだね。いらんか笑
消そう笑
R入れよう〜！

↑スレッドトップの一覧更新しました！

**Comment by k-kudo-hub** [comment]
migrationファイル自体はひとつで済むんだっけ？

**Comment by toshiro-koba** [comment]
多分一つでやります。

```ruby
def change
  Log.destroy_all
  ActiveRecord::Base.connection.execute('alter table languages auto_increment = 1;')
  languages = %w(Bar Baz Foo)
  languages.each do |language|
    Language.create(name: language)
  end
end
```

こんな感じでできると思う。
まだ試してないけど

**Comment by k-kudo-hub** [comment]
いいっすね〜！
これで行ければだいぶ楽になるね

**Comment by toshiro-koba** [comment]
ね〜！
とりあえず初期データ投入はこれでいいかな？
後から追加するときは`Language.create`の部分だけ書く感じで。

あとは言語一覧だね。
これはもうちょっと寝かせて決める方が安定しそうな気がしてる

**Comment by k-kudo-hub** [comment]
> とりあえず初期データ投入はこれでいいかな？
> 後から追加するときはLanguage.createの部分だけ書く感じで。

そのmigrationファイルが成功するようならOK！
書くっていうよりは書き足す感じよね、いいと思う👍

> これはもうちょっと寝かせて決める方が安定しそうな気がしてる

まぁあとで書き足せるから、俺は一旦決めちゃってもいいと思うよ笑

**Comment by k-kudo-hub** [comment]
Perl と Scala と COBOL くらいは入れとく？古いけど有名どころだし

**Comment by toshiro-koba** [comment]
いいね！追加しました！👍

**Comment by toshiro-koba** [comment]
まぁあとで書き足せるから、俺は一旦決めちゃってもいいと思うよ笑

変に長引かせる理由も無いしな笑、決めちゃおう

**Comment by toshiro-koba** [comment]
DartとMATLAB追加したい！どちらも自分で使う予定はないけど笑

**Comment by k-kudo-hub** [comment]
どっちもはじめて聞いたけどとりあえず入れるか笑

**Comment by toshiro-koba** [comment]
ごめんやっぱDartは無しで🙏
goよろしくgoogleが作ったフロント向け言語だけどTypeScriptと比べると勢いがなさそう...

MATLABは数値解析系だね。

MATLABだけ追記しましたあ！！

**Comment by k-kudo-hub** [comment]
おけ！👍

**Comment by toshiro-koba** [comment]
今日(5/1)の21時までに変更なかったら一旦確定ということでissue閉じます！

**Comment by toshiro-koba** [comment]
> 今日(5/1)の21時までに変更なかったら一旦確定ということでissue閉じます！

ごめん、issueは閉じないわw`need discussion`のタグと`green light`のタグ取り替えます。
何度も通知申し訳ない🙇

**Comment by k-kudo-hub** [comment]
まだこれ取り掛かってなかったらNode.js いれてくれると嬉しい笑
