### ISSUE TITLE
サイドバーを導入する

### ISSUE THREAD

**Issue by k-kudo-hub** [k-kudo-hub/error_note_sample#56]
## 実現したいこと
- サイドバーを導入し、トップページをリッチにする
- シンプルさを保ちながら、ユーザビリティを高める

## サイドバーの内容
- ログの言語ランキング
- ストックされているノートランキング

## 実装のタイミング
- Vue.jsを優先しつつ、手が空いたタイミングで実装する

**Comment by k-kudo-hub** [comment]
## デザイン案
![image](https://user-images.githubusercontent.com/68951522/117524344-f4932900-aff7-11eb-9b9f-b094625adaae.png)

**Comment by toshiro-koba** [comment]
おおお、かなりリッチになりましたね！
いいと思います！👍

**Comment by k-kudo-hub** [comment]
コメントありがとう！
これはFigmaで作った案なので、 #58 をMerge次第実装します🔥
