### ISSUE TITLE
ログ一覧テーブルのデザインを整える

### ISSUE THREAD

**Issue by k-kudo-hub** [k-kudo-hub/error_note_sample#57]
## 実現したいこと
- ログ一覧テーブルのデザインをいい感じに整える
- 今のところシステム感がすごいので、エンド向けに直す

## 具体的な実現手段
- テーブル構造を廃止
- ユーザー情報、言語情報、ストック数を追加
- 各フォントのサイズ、色調、デザインを調整

## 実装のタイミング
- Vue.jsを優先しつつ、手が空いたタイミングで実装する

**Comment by toshiro-koba** [comment]
> 今のところシステム感がすごいので、エンド向けに直す

ここめっちゃイケてる(使いたい)ってしていきたいよね〜ほんと

**Comment by k-kudo-hub** [comment]
そう！とりあえずシステム感を早めに消したい笑

**Comment by k-kudo-hub** [comment]
新デザイン案A
<img width="702" alt="531b3f6261cd7adcceb71a35b62b4b0c" src="https://user-images.githubusercontent.com/68951522/116813722-23d90e80-ab90-11eb-9d10-160ab0506e0f.png">

**Comment by k-kudo-hub** [comment]
## 新デザイン案A（2）言語ごとにカラーを変更
<img width="661" alt="0776703e4b73f0f0983e54a59949b103 (1)" src="https://user-images.githubusercontent.com/68951522/116835028-a2b76100-abfb-11eb-9d59-60950ff30195.png">

**Comment by toshiro-koba** [comment]
レイアウト綺麗〜！
色分けは言語多いしちょっと大変な気がするけど、どうだろ

**Comment by k-kudo-hub** [comment]
DPRで実装サンプル出してるから見てみて～✋

**Comment by toshiro-koba** [comment]
scssで定義してくれてるのね。なるほど。
trimで文字列をケアしてるの流石っす！

実装は問題なさそうね

**Comment by k-kudo-hub** [comment]
5/6 追記
- DPRのコードをmigrationファイルに合わせて書き換えた
- 初期データにある言語全てで正常にスタイルが当たることを確認した
