### ISSUE TITLE
Rails6.1.3.2へアップデート

### ISSUE THREAD

**Issue by toshiro-koba** [k-kudo-hub/error_note_sample#60]
セキュリティフィックスのアップデートが入ったらしいです。

[Rails versions 6\.1\.3\.2, 6\.0\.3\.7, 5\.2\.4\.6, and 5\.2\.6 have been released\! \| Riding Rails](https://weblog.rubyonrails.org/2021/5/5/Rails-versions-6-1-3-2-6-0-3-7-5-2-4-6-and-5-2-6-have-been-released/)

現在使用しているバージョンは6.1.3.1

お手隙の際にささっとやっちゃいますか

**Comment by k-kudo-hub** [comment]
バックエンドに一任します！🙆‍♂️

**Comment by toshiro-koba** [comment]
今週中にはサクッとやっちゃいますわ！

> 今後1ヶ月に1回くらいアプデの確認とかセキュリティの見直しとかしてもいいですね👍

いいね。月末とかに見直しできるようリストでも作りますかね

**Comment by k-kudo-hub** [comment]
色々任せきりで申し訳ない！よろしくお願いします🙏
