### ISSUE TITLE
リファクタリング_rubocopで整形したところ周り

### ISSUE THREAD

**Issue by toshiro-koba** [k-kudo-hub/error_note_sample#65]
# やること
- バックエンドのリファクタリング
- rubocopの警告レベル`W `以上は解消します。

## なぜやるか
rubocop用issue作成からmergeまで時間が経ち、
コード整形よりconflict解消を優先したため。
関連 #33 

## 実施時期
Phase1.5

### その他
- ブランチ名は`feature-refactoring-イシュー番号`で出そうと思ってます。
- リファクタリングの場合でも、本来の実装手順に沿ってPRは作る方がいいと思うのですが、どうでしょうか？

**Comment by k-kudo-hub** [comment]
> リファクタリングの場合でも、本来の実装手順に沿ってPRは作る方がいいと思うのですが、どうでしょうか？

もちろんPRは作りましょう。PR出さないとコードについて議論できませんので🙏
基本的に例外なく、Issue作って議論→開発作業→PR→レビュー→Mergeで行きたいです

**Comment by toshiro-koba** [comment]
コメントありがとうございます。

> 基本的に例外なく、Issue作って議論→開発作業→PR→レビュー→Mergeで行きたいです

了解です👍
