### ISSUE TITLE
modelに関する単体テストを作成

### ISSUE THREAD

**Issue by toshiro-koba** [k-kudo-hub/error_note_sample#68]
# やること
- model(user, log, stock)に関する単体テストをRSpecで作成
- gem RSpec, FactoryBot, Fakerの導入

## なぜやるか
デグレーションを防ぐため。

## 実施時期
Phase1.5

### その他
- 今後のPRでテストを書くかどうかは任意で良いと考えてます。
(テンポ良く実装して、アプリの使いやすさを向上させたいため)
- 結合テストは別のissueで作成します。
- テストは基本的にバックエンド担当が責任を持つ

**Comment by k-kudo-hub** [comment]
確認しました！

> gem RSpec, FactoryBot, Fakerの導入

pry-railsとかも入れてなかったと思うので、一緒に入れてくれると助かります🙏

> Phase1.5

爆速実装さすがです…！
rubocopもやって頂いているので、タスクオーバーには気をつけてくださいね😅笑

**Comment by toshiro-koba** [comment]
> pry-railsとかも入れてなかったと思うので、一緒に入れてくれると助かります🙏

こちら、`binding.irb`で代用できませんか？
`binding.irb`では機能が足りない等ありましたら`pry-rails`も導入します。

> rubocopもやって頂いているので、タスクオーバーには気をつけてくださいね😅笑

お気遣いあざっす！
仮に実装の時間が取れなさそうであればなるはやで申告します🙇

**Comment by k-kudo-hub** [comment]
> こちら、binding.irbで代用できませんか？
binding.irb知らなかった…全然こっちで問題ないし、なんならこっちがスタンダードですね！🙆‍♂️

**Comment by toshiro-koba** [comment]
> binding.irb知らなかった…全然こっちで問題ないし、なんならこっちがスタンダードですね！🙆‍♂️

自分も最近知りました💦

では手が空いた時に実装取り掛かります🏃

**Comment by toshiro-koba** [comment]
こちらのissueクローズします🙇
