### ISSUE TITLE
ログ詳細画面のスタイルを見直す

### ISSUE THREAD

**Issue by k-kudo-hub** [k-kudo-hub/error_note_sample#70]
## 実現したいこと
- ログ詳細画面のデザインを根本的に見直す

## 具体的には
- テーブル構造の廃止
- エラー文や解決法にwidthを確保し、視認性を上げる

## 実装のタイミング
- Phase1.5

**Comment by k-kudo-hub** [comment]
特に凝る気はないので大丈夫！時間もそんなにかけないつもりです笑
フロントとしてはIssue消化も順調なので、このIssueでPhase1.5（フロント）は最後でもいいかなと思ってます👍

ポートフォリオのデザインありがとう笑
参考にさせていただきます

**Comment by toshiro-koba** [comment]
> フロントとしてはIssue消化も順調なので、このIssueでPhase1.5（フロント）は最後でもいいかなと思ってます👍
なるほどです！
お手隙の際に実装お願いします🙇

**Comment by k-kudo-hub** [comment]
## デザイン案（2021/05/12作成）

![7ece04f995a9d641be51d65ad7d5c9eb](https://user-images.githubusercontent.com/68951522/117897281-6e2f5d80-b2fd-11eb-96aa-3980a5129de1.png)

**Comment by toshiro-koba** [comment]
おおお！
赤と緑のbackground-colorのおかげですごく分かりやすいです！🤩

個人的にはエラー概要(タイトル、言語), 最終更新日の順にするとより分かりやすくなるかなと思います！
そして左揃えで統一する方が好きですね(これは個人的な好みですが笑)
<img width="484" alt="117897281-6e2f5d80-b2fd-11eb-96aa-3980a5129de1_png" src="https://user-images.githubusercontent.com/56726628/117958079-a2366d00-b355-11eb-8120-1d327cc667e0.png">

**Comment by k-kudo-hub** [comment]
コメントありがとう！
表示順の案についてはいいと思います！タイトル→言語→最終更新日順に並び替えてみます🙆‍♂️
全体の左揃えは見送らせてください笑（サイト全体のデザインに影響してしまうので）

**Comment by toshiro-koba** [comment]
採用ありがとう！
全体のデザインはお任せします🙏
