### ISSUE TITLE
ユーザー新規登録処理が動かない

### ISSUE THREAD

**Issue by k-kudo-hub** [k-kudo-hub/error_note_sample#74]
## バグの状況
- ユーザー新規登録ボタン(header内、/users/sign_up)を押すとエラーメッセージが発現する

## 原因
- おそらく`app/controllers/users/registrations_controller.rb `が消失していることが原因

## エラー画面
<img width="1421" alt="cdbc4a339fc0fc6492ee4603eaed19c0" src="https://user-images.githubusercontent.com/68951522/117971797-4d025780-b365-11eb-9bf5-ece7c78c0422.png">

**Comment by k-kudo-hub** [comment]
ここで消しちゃってる模様。確認ミスで申し訳ない🙏
https://github.com/k-kudo-hub/error_note_sample/pull/71/files

**Comment by toshiro-koba** [comment]
すみません確認できてませんでした🙇
修正します。

**Comment by toshiro-koba** [comment]
すみません、誤ってmasterブランチに直接pushしてしまいました。
申し訳ありません。

**Comment by k-kudo-hub** [comment]
コード確認しました！修正ありがとうございます🙆‍♂️
（仕事じゃないから謝らなくて大丈夫だよ💦）
